---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Images
- type: document
  path: content/galerie.json
  label: Galerie des JFAC
- type: document
  path: content/partners.json
  label: Partenaires
- type: heading
  label: Pages
- type: document
  path: content/pages/home.json
  label: Accueil
- type: document
  path: content/jfac19.json
  label: JFAC
upload_dir: refacc/images
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv/public"
  instant_preview_command: yarn forestry-preview
